version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  "build and test":
    branches:
      ignore:
        - master
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    "default":
      jobs:
        - "build and test"
