apiVersion: apps/v1
kind: Deployment
metadata:
  name: decisionservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decisionservice
  template:
    metadata:
      labels:
        app: decisionservice
    spec:
      containers:
        - name: decisionservice
          image: jtutzo/katawolf/decisionservice
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: decisionservice-config
                  key: port
          resources:
            limits:
              memory: 256Mi
              cpu: 125m
            requests:
              cpu: 70m
              memory: 200Mi
